### ISSUE TITLE
Armv7 builds require libstdc++.so.6

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/NetworkTablesCore#18]
The cross compiled builds require the specific version of libstdc++.so.6. We should embed it in the ArmStandalone DLL, and if we detect it, load the library. We also don't have a way to cross compile builds for Pi 1. So we either need to find one, or probably drop support for arm v6

**Comment by ThadHouse** [comment]
So the file is embedded and extracts properly. However I can't currently find a way to set LD_LIBRARY_PATH or LD_PRELOAD the library automatically, but I'm looking into it.

**Comment by jkoritzinsky** [comment]
I'd suggest looking at `System.Environment.SetEnvironmentVariable`.  I'm not sure if it will export the variable to the right scope, but that might be what you want.

**Comment by ThadHouse** [comment]
I tried already. It wouldn't accept it. I think mono is loading the standard libstdc++.so.6 on startup, and there's no way to replace that at runtime I don't think. I was able to figure out which environmental variable it gets set to in the console when setting LD_LIBRARY_PATH, however setting that at runtime still didn't work.

**Comment by jkoritzinsky** [comment]
Right... I wasn't thinking that mono would be loading the standard libstdc++.so.6...

**Comment by ThadHouse** [comment]
Which means there's no way to do this other the a mid program restart, which doesn't seem like a good idea. I'll just write up some better docs and a better error message for that specific case. It already extracts the library correctly, so they don't have to download it ever.

**Comment by ThadHouse** [comment]
I got better error messages implemented, and official is having to do this same thing, so I'm closing this.
