### ISSUE TITLE
Running two programs that use ntcore on the same machine causes a crash.

### ISSUE THREAD

**Issue by jkoritzinsky** [robotdotnet/NetworkTablesCore#20]
I've been working on a RobotDotNet SmartDashboard equivalent.  One thing I've noticed in testing is when you run two instances of programs that use this library, an IOException is thrown when the code tries to verify the ntcore library.  One way to solve this is to get a new temporary path and extract to that instead if this scenario happens.

**Comment by ThadHouse** [comment]
Is it crashing at the ReadAllBytes method (Line 203 in InteropUtilites.cs)? I'll just add a catch around everything and if we ever get an IOException extract to a unique file.

**Comment by jkoritzinsky** [comment]
I think it's the ReadAllBytes call that's causing the crash.

**Comment by ThadHouse** [comment]
I commited a fix that should work, but I don't have time to test it right now. It extracts to a unique temp file name if it catches an IO error. The only issue with this is that the file does not automatically delete, as I've never actually seen delete on exit work. But it should be fine on the dashboard.

**Comment by jkoritzinsky** [comment]
I'll test it out and let you know.

**Comment by ThadHouse** [comment]
It might be worth it to do the comparison thing only on the RoboRIO. Everywhere else, we can always store to a temporary file, and set the delete on exit flag. The reason this doesn't work on the RoboRIO is that the program rarely stops, and is instead killed, where the delete on exit flag won't work. I'll look into that some more when I have time, but the work around now should at least work.

**Comment by ThadHouse** [comment]
So PR #21 changes to always using a temp file. The reason for the funky extraction originally was that the ntcore library was 7mb, and extracting that every time was costly. However, its not down to about 500kb, so its ok to be like java and constantly extract it to a new unique file every time. So test the lastest #21 PR builds too and see if that also fixes your problem.

**Comment by jkoritzinsky** [comment]
This has been fixed by PR #21.
