### ISSUE TITLE
Add Sandcastle generator

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/NetworkTablesCore#5]
We are going to have an external build for sandcastle, however we still need a sandcastle project in this repository to create the XML file if the library is built manually.

**Comment by jkoritzinsky** [comment]
I'm going to set up this one and the one in the WPILib repo to only generate the Intellisense XML file.  That way we have less cruft we need to support.

**Comment by jkoritzinsky** [comment]
Done.
